## Import Modules

In [105]:
import cv2 as cv
import numpy as np

## Part A

In [173]:
def isolate(img, minDist, p1, p2, minRad, maxRad):
  grayscale = cv.cvtColor(img, cv.COLOR_BGR2GRAY)
  circles = cv.HoughCircles(grayscale,cv.HOUGH_GRADIENT,1,minDist,
                              param1=p1,param2=p2,minRadius=minRad,maxRadius=maxRad)
  circles = np.uint16(np.around(circles))[0]
  for circle in circles:
    x = circle[0]
    y = circle[1]
    rad = circle[2]
    # Draw the red circle at the center of the object
    cv.circle(img,(x,y),3,(0,0,255),4)
    # Draw the green circle around the object
    cv.circle(img,(x,y),rad,(0,255,0),4)
  return img

def displayImg(img):
  cv.imshow('Detected Circles',img)
  cv.waitKey(0)
  cv.destroyAllWindows()

target = cv.imread('./images/circles_target.jpg', cv.IMREAD_COLOR)
isolated = isolate(target, 20, 50, 30, 40, 65)
displayImg(isolated)


## Part B

In [310]:
def isolate(img, minDist, p1, p2, minRad, maxRad):
  grayscale = cv.cvtColor(img, cv.COLOR_BGR2GRAY)
  edges = cv.Canny(grayscale, 12000, 2500, apertureSize=7)
  lines = cv.HoughLines(edges, 1.2, .6*np.pi/180, 130)
  print(lines)
  for r_theta in lines:
    arr = np.array(r_theta[0], dtype=np.float64)
    r, theta = arr
    a = np.cos(theta)
    b = np.sin(theta)
    x1 = int(a*r + 1000*(-b))
    y1 = int(b*r + 1000*(a))
    x2 = int(a*r - 1000*(-b))
    y2 = int(b*r - 1000*(a))
 
    cv.line(img, (x1, y1), (x2, y2), (0, 255, 0), 1)
  return img

def displayImg(img):
  cv.imshow('Detected Circles',img)
  cv.waitKey(0)
  cv.destroyAllWindows()

target = cv.imread('./images/lines_target.jpg', cv.IMREAD_COLOR)
isolated = isolate(target, 20, 50, 30, 40, 65)
displayImg(isolated)


[[[-3.2760001e+02  2.4713862e+00]]

 [[ 2.4960001e+02  0.0000000e+00]]

 [[-1.6920001e+02  2.4609141e+00]]

 [[-6.3600002e+01  3.1311207e+00]]

 [[-3.2280002e+02  2.4713862e+00]]

 [[ 3.8880002e+02  1.5812683e+00]]

 [[-3.1800000e+02  2.4609141e+00]]

 [[-1.8000000e+02  2.4713862e+00]]

 [[-1.7520001e+02  2.4609141e+00]]

 [[ 1.2480000e+02  1.5707964e+00]]

 [[-1.6440001e+02  2.4504423e+00]]

 [[ 3.9360001e+02  1.5707964e+00]]

 [[-3.3240002e+02  2.4818583e+00]]

 [[ 2.9760001e+02  1.5707964e+00]]

 [[-1.7400000e+02  2.4713862e+00]]

 [[ 3.2640002e+02  8.9011788e-01]]

 [[ 3.2880002e+02  8.7964594e-01]]

 [[ 3.3360001e+02  8.9011788e-01]]

 [[-1.7160001e+02  2.4504423e+00]]

 [[ 2.9280002e+02  1.5707964e+00]]

 [[ 5.5680005e+02  9.0058988e-01]]

 [[ 3.3600000e+02  8.7964594e-01]]

 [[ 2.5320001e+02  1.0471975e-02]]]
