In [1]:
import cv2 as cv
import numpy as np

## Load Image

In [87]:
def displayImg(img):
  cv.imshow('Detected Circles',img)
  cv.waitKey(0)
  cv.destroyAllWindows()

image = cv.imread('./images/Img1.png', cv.IMREAD_GRAYSCALE)

displayImg(image)

## Blur

In [89]:
def blur(img, blurDepth):
  blurred = np.zeros(img.shape, dtype="uint8")
  for i in range(len(img)):
    for j in range(len(img[0])):
      runningTotal = 0
      pixelsSeen = 0
      for x in range(max(0, i-blurDepth), min(len(img), i+blurDepth)):
        for y in range(max(0, j-blurDepth), min(len(img[0]), j+blurDepth)):
          pixelsSeen +=1
          runningTotal += int(img[x][y])
      blurred[i][j] = int(runningTotal//pixelsSeen)
  return blurred
image = cv.imread('./images/Img1.png', cv.IMREAD_GRAYSCALE)


displayImg(image)
blurred = blur(image, 3)
displayImg(blurred)

### Median Filter

In [91]:
def median(img, blurDepth):
  blurred = np.zeros(img.shape, dtype="uint8")
  for i in range(len(img)):
    for j in range(len(img[0])):
      pixelsSeen = []
      for x in range(max(0, i-blurDepth), min(len(img), i+blurDepth)):
        for y in range(max(0, j-blurDepth), min(len(img[0]), j+blurDepth)):
          pixelsSeen.append(img[x][y])
      blurred[i][j] = sorted(pixelsSeen)[len(pixelsSeen)//2]
  return blurred
image = cv.imread('./images/Img1.png', cv.IMREAD_GRAYSCALE)

print(image.dtype)
displayImg(image)
blurred = median(image, 2)
print(blurred)
displayImg(blurred)

uint8
[[255  56  57 ...  46  45  45]
 [254  55  56 ...  47  46  46]
 [254  55  55 ...  49  46  46]
 ...
 [255  22  22 ...  47  51  53]
 [254  24  24 ...  47  51  51]
 [254  24  24 ...  47  51  51]]


## Sharpening

### Laplacian Mask

In [134]:
def laplacian(img):
  sharpened = np.zeros(img.shape, dtype="uint8")
  for i in range(1, len(img)-1):
    for j in range(1, len(img[0])-1):
      maskValue = int(img[i+1][j]) + int(img[i-1][j]) + int(img[i][j+1]) + int(img[i][j-1]) - 4*int(img[i][j])
      if maskValue < 0:
        sharpened[i][j] = 255
      else:
        sharpened[i][j] = 0

  return sharpened
image = cv.imread('./images/Img1.png', cv.IMREAD_GRAYSCALE)

print(image.dtype)
displayImg(image)
sharpened = laplacian(median(image, 3))
displayImg(sharpened)

uint8


### Robert Cross

In [119]:
def robertCross(img):
  sharpened = np.zeros(img.shape, dtype="uint8")
  for i in range(1, len(img)-1):
    for j in range(1, len(img[0])-1):
      maskValue = int(img[i][j]) - int(img[i+1][j+1])
      sharpened[i][j] = max(int(img[i][j]) - abs(maskValue), 0)

  return sharpened
image = cv.imread('./images/Img1.png', cv.IMREAD_GRAYSCALE)

print(image.dtype)
displayImg(image)
sharpened = robertCross(image)
displayImg(sharpened)

uint8


In [162]:
def sobel(img):
  sharpened = np.zeros(img.shape, dtype="uint8")
  for i in range(1, len(img)-1):
    for j in range(1, len(img[0])-1):
      pix0 = -1 * int(img[i-1][j-1])
      pix1 = -2 * int(img[i-1][j])
      pix2 = -1 * int(img[i-1][j+1])
      pix3 = 0
      pix4 = 0
      pix5 = 0
      pix6 = int(img[i+1][j-1])
      pix7 = 2 * int(img[i+1][j])
      pix8 = int(img[i+1][j+1])

      maskValue = (pix0+pix1 +pix2 +pix3 +pix4 +pix5 +pix6 +pix7 +pix8) // 9
      sharpened[i][j] = int(img[i][j]) - maskValue

  return sharpened 
image = cv.imread('./images/Img1.png', cv.IMREAD_GRAYSCALE)

print(image.dtype)
displayImg(image) 
sharpened = sobel(image)
displayImg(sharpened)

uint8


: 